---
title: "Week 3 Assignment: R Markdown Presentation & Plotly"
author: "Martina Melinscak"
date: 'March 29, 2017'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Installing Plotly

```r
install.packages("plotly")
library(plotly)
```


##Scatterplot - Plotting Markers and Lines


```{r, eval=FALSE, message=FALSE}
library(plotly)
trace_0 <- rnorm(150, mean = 5)
trace_1 <- rnorm(150, mean = 0)
trace_2 <- rnorm(150, mean = -5)
x <- c(1:150)

data <- data.frame(x, trace_0, trace_1, trace_2)

plot_ly(data, x = ~x, y = ~trace_0, name = 'trace 0', type = 'scatter', mode = 'lines') %>%
  add_trace(y = ~trace_1, name = 'trace 1', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'trace 2', mode = 'markers')
```


```{r, echo=FALSE, message=FALSE}

library(plotly)
trace_0 <- rnorm(150, mean = 5)
trace_1 <- rnorm(150, mean = 0)
trace_2 <- rnorm(150, mean = -5)
x <- c(1:150)

data <- data.frame(x, trace_0, trace_1, trace_2)

plot_ly(data, x = ~x, y = ~trace_0, name = 'trace 0', type = 'scatter', mode = 'lines', colors = 'set1') %>%
  add_trace(y = ~trace_1, name = 'trace 1', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'trace 2', mode = 'markers')

```

